### PR TITLE
Removing Perl apps man pages

### PR DESCRIPTION
**Pull request by wallyqs**

### CODE REVIEW

**Comment by tcahill** [comment]
@zquestz @alextoombs

**Comment by alextoombs** [comment]
I am incapable of verifying the diff, but LGTM if green.

**Comment by tcahill** [comment]
http://tc.apcera.net/viewLog.html?buildId=119857&tab=buildResultsDiv&buildTypeId=SystemTestsApceraSetup_ApceraSetupDeployTestBranchesVSphereThreaded

**Comment by zquestz** [comment]
LGTM

**Pull request merged**
