### PR TITLE
Quote template path from example-ruby-manifest app

### PR DESCRIPTION
**Pull request by wallyqs**
@variadico

### CODE REVIEW

**Comment by variadico** [comment]
We need to change the route as well.

```
ports: [
  {
    number: 0,
    routes: [
      {   
        type: "http",
        endpoint: "example-ruby-manifest.vagrant.apcera.net",
      }   
    ]   
  }
]
```

**Comment by alextoombs** [comment]
`endpoint: "auto"` to the rescue?

**Comment by alextoombs** [comment]
LGTM

**Comment by variadico** [comment]
That will do it, but I think we need to update the system tests.

**Comment by alextoombs** [comment]
If the tests were trying to validate that the app was up at `foo.vagrant.apcera.net`, they'd already be failing, right?

**Comment by variadico** [comment]
Yeah, that's right. There is some code the does a search and replace on a URL.
https://github.com/apcera/continuum/blob/7aebd0e23f539ebb95f4596a4fef1e11d4717639/testing/system/spec/staging/manifest_spec.rb#L37

**Pull request merged**
