### PR TITLE
Added nats-ping app to sample-apps, needed for docs and training

### PR DESCRIPTION
**Pull request by lparis**
@zquestz @rjdavidburke Adding nats-ping app. We need this for docs and training. Was in continuum-sample-apps.

### CODE REVIEW

**Comment by zquestz** [comment]
I believe this was moved to test-apps. If we move it back to sample-apps we should remove it from there and also verify it isn't used in the test suite (might need to change the sample_app method to test_app)

**Comment by lparis** [comment]
How can I verify this?

**Comment by zquestz** [comment]
Yep it was. https://github.com/apcera/test-apps/tree/master/nats-ping

**Comment by zquestz** [comment]
We do not use it in the test suite, should be safe to move.

**Comment by lparis** [comment]
@zquestz Can I merge this? I am not familiar with add/removing apps from the test suite, so I don't think I can do that.

**Comment by zquestz** [comment]
Test suite doesn't need changes, we don't use this app. We just need to remove it from the test-apps repo, now that it is being moved back to the sample-apps repo.

**Comment by lparis** [comment]
OK, can I ask you to do that please. I am not familiar with that repo. In the meantime, can I merge this?

**Comment by zquestz** [comment]
This can be merged.

**Comment by zquestz** [comment]
LGTM

**Comment by zquestz** [comment]
That repo is literally at github.com/apcera/test-apps. If you can remove it that would be great. Otherwise I will find someone to do it.

**Comment by lparis** [comment]
OK, I will do it.

**Pull request merged**
