### PR TITLE
Improve indentation in demo-node-chat sample app

### PR DESCRIPTION
**Pull request by ofctlo**
Improves readability, maintainability.

### CODE REVIEW

**Comment by ofctlo** [comment]
@zquestz @rusher81572

**Comment by rusher81572** [comment]
Thanks. Did you use a program to automatically do this? If so, please tell me how =) I am used to Java development in an IDE that does this automatically but I am using Sublime for NodeJS work.

**Comment by ofctlo** [comment]
I didn't, although there probably is a way. I just find it cathartic to fix this sometimes.

**Comment by variadico** [comment]
In JavaScript, autoformatters tend to be called "beautifiers". There are a bunch of [online beautifiers](https://www.google.com/search?q=javascript+beautifier) and it even looks like there are also some [beautifiers for Sublime Text](https://www.google.com/search?q=sublime+text+javascript+beautifier) as well. :)

**Comment by rusher81572** [comment]
Closing since code has been significantly changed since this PR.

**Pull request closed without merging**
