### PR TITLE
Updates all ruby sample apps to support Ruby 2.2.5

### PR DESCRIPTION
**Pull request by lilirui**
Updates all ruby sample apps to support Ruby 2.2.5

Pair with https://github.com/apcera/package-scripts/pull/142

@variadico @zquestz @johnSchnake @yaso195

### CODE REVIEW

**Comment by variadico** [comment]
LGTM, but we should make sure to run system tests in case some Ruby app breaks when it's updated.

**Comment by lilirui** [comment]
Definitely, test is running, we also have changes in continuum.

**Comment by zquestz** [comment]
LGTM

**Comment by lilirui** [comment]
Green test at http://tc.apcera.net/viewLog.html?buildId=310057&tab=buildResultsDiv&buildTypeId=SystemTests_DeployTestBranchesVSphereMultiCentral

**Pull request merged**
