### PR TITLE
Added Docker version of nats-ping

### PR DESCRIPTION
**Pull request by lparis**
@rusher81572 @zquestz Phil's awesome Docker version of nats-ping.

### CODE REVIEW

**Comment by rusher81572** [comment]
1. The ReadME should explain how to connect the app to a nats server and the format for the NATS_URI envar.

2. The Dockerfile should be in the root directory. If both nats-ping.go work, there is no reason to have multiple copies.

**Comment by lparis** [comment]
Yes to 1, no to 2. Want to keep them separate to avoid confusion. Will do it later.

**Comment by lparis** [comment]
But the code could be merged into 1 file.

**Comment by rusher81572** [comment]
I think it is best to keep things simple, lean, and mean.

**Comment by zquestz** [comment]
I have to agree, no need to have duplicates. the Dockerfile can be in the root!

**Comment by lparis** [comment]
@rusher81572 @zquestz OK, fixed now, thanks

**Comment by rusher81572** [comment]
LGTM

**Pull request merged**
