### PR TITLE
Vendor all dependencies for ruby sample apps.

### PR DESCRIPTION
**Pull request by krobertson**
This adds the vendored dependencies for all ruby sample apps. This will
help with reducing deployment time for users deploying, and also help
with internal CI to speed up test times and reduce the external
dependency on rubygems.org.

@Arvinderpal @juanman2 @zquestz

### CODE REVIEW

**Comment by zquestz** [comment]
LGTM!

**Comment by Arvinderpal** [comment]
LGTM

**Comment by krobertson** [comment]
Paused for a bit... the increase in size caused 3 package quota tests to fail. Posting a PR for those, then will merge.

**Comment by juanman2** [comment]
OK to MERGE

**Pull request merged**
