### PR TITLE
Update sample apps to use recent package versions - ENGT-6991

### PR DESCRIPTION
**Pull request by zquestz**
Updates all ruby sample apps to support Ruby 2.2.4.

@tw4dl @schancel @lloydde @olegshaldybin

### CODE REVIEW

**Comment by tw4dl** [comment]
LGTM when test passes. Also tried a couple samples (rails and ruby).

**Comment by zquestz** [comment]
Also I will squash. =)

**Comment by krobertson** [comment]
LGTM.

I wouldn't squash everything.  Maybe just a few of them. Looking at this as a single commit would be impossible. Without the separate commits, I wouldn't have been able to reviewed the changes.

**Comment by zquestz** [comment]
Rebased intelligently. One commit per app, plus one to bring to 2.2.4 from 2.2.3.

**Comment by tw4dl** [comment]
LGTM - Nice organization of commits.

**Pull request merged**
