### PR TITLE
Added sample Go event streaming client app

### PR DESCRIPTION
**Pull request by tstatler**
@alextoombs @shobhit85

### CODE REVIEW

**Comment by tstatler** [comment]
It might be an issue with my setup, but I'm getting an error when I run the app:

```
go run main.go https://api.cosmic.apcera-platform.io/v1/wamp job::/apcera
Creating WAMP client against "https://api.cosmic.apcera-platform.io/v1/wamp" with token "Bearer eyJ0eXAiOiIiLCJhbGciOiIifQ.eyJpc3MiOiJnb29nbGVfYXV0aF9zZXJ2ZXJAYXBjZXJhLm1lIiwiYXVkIjoiYXBjZXJhLm1lIiwiaWF0IjoxNDY3NDE0MjQwLCJleHAiOjE0Njc1MDA2NTAsInBybiI6InRpbS5zdGF0bGVyQGFwY2VyYS5jb20iLCJjbGFpbXMiOlt7Iklzc3VlciI6ImF1dGhfc2VydmVyQGFwY2VyYS5tZSIsIlR5cGUiOiJhdXRoVHlwZSIsIlZhbHVlIjoiZ29vZ2xlVXNlckluZm8ifV19.MEUCIQDOV6cjOT9vlc5_65oNgUfne6_2K5k1S_SoWTw6j628bwIgL2EeTdSDZFY3Ad3UEne12IAjAWO3I0wvv5XokNzLsVE"...
Target url: "wss://api.cosmic.apcera-platform.io/v1/wamp" 
Failed to create WAMP client: websocket: bad handshake
exit status 1
```

**Comment by tstatler** [comment]
@alextoombs @shobhit85 

Are you guys able able to get the Go sample to work on your cluster/s?

**Comment by shobhit85** [comment]
Yes @tstatler I just tried on my virtualbox cluster and seems to work fine.

**Comment by tstatler** [comment]
That must have been it, thanks for testing.

**Pull request merged**
